version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    # Add assignees
    assignees:
      - 'PauloHSOliveira'
# notifications
notifications:
  - type: 'pull_request'
    parameters:
      branches:
        - 'develop'
