version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'PauloHSOliveira'
    commit-message:
      prefix: '[NPM] Lib update'
    labels:
      - 'npm'
      - 'dependencies'
    open-pull-requests-limit: 5
    target-branch: 'develop'
